# Generated by Django 5.2.7 on 2025-10-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_lab_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lab_technician', 'Lab Technician'), ('lab_admin', 'Lab Administrator')], default='lab_technician', max_length=20),
        ),
    ]
