# Generated by Django 5.2.8 on 2025-11-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patientmaster_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmaster',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
