# Generated by Django 5.2.7 on 2025-10-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patientmaster_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienttest',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patienttest',
            name='result_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
