# Generated by Django 5.2.8 on 2025-11-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patientmaster_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmaster',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
