# Generated by Django 5.2.7 on 2025-10-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestMaster',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('normal_range', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('default_value', models.CharField(blank=True, max_length=50, null=True)),
                ('lower_range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upper_range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.lab')),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testgroupmaster')),
            ],
        ),
    ]
