# Generated by Django 5.2.8 on 2025-11-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmaster',
            name='compulsory',
            field=models.BooleanField(default=False),
        ),
    ]
