# Generated by Django 5.2.7 on 2025-10-31 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_remove_lab_id_alter_lab_lab_id'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Methods',
            fields=[
                ('method_id', models.AutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=150)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
                ('method_description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labs.lab')),
            ],
        ),
    ]
