# Generated by Django 5.2.7 on 2025-10-31 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='methods',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.testmaster'),
        ),
    ]
