# Generated by Django 5.2.7 on 2025-10-31 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_remove_lab_id_alter_lab_lab_id'),
        ('tests', '0003_methods_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroupmaster',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labs.lab'),
            preserve_default=False,
        ),
    ]
