# Generated by Django 5.2.7 on 2025-10-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_testgroupmaster_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmaster',
            name='default_value',
        ),
        migrations.RemoveField(
            model_name='testmaster',
            name='normal_range',
        ),
    ]
