# Generated by Django 5.2.7 on 2025-10-31 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_testmaster_default_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methods',
            name='test',
        ),
        migrations.AddField(
            model_name='testmaster',
            name='methods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.methods'),
        ),
    ]
