# Generated by Django 4.2.26 on 2025-11-07 13:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('status', models.BooleanField(default=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.lab')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('upi', 'UPI')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
