# Generated by Django 5.2.7 on 2025-10-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='id',
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
